### ISSUE TITLE
Add a license? Maybe a readme?

### ISSUE THREAD

**Issue by kingcons** [sellout/cl-gravatar#1]
Sellout,

This is a small lib but I thought it might make a fun addition to quicklisp. There are concerns about the lack of a readme and license though. Any interest in adding them?

**Comment by sellout** [comment]
Yeah, sure. I’'ll get that in there tonight.

**Comment by sellout** [comment]
Ok, this is in.

**Comment by kingcons** [comment]
Thanks. :)
